# Generated by Django 5.1 on 2025-02-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_purpose',
            field=models.CharField(blank=True, help_text='Reason for using the office vehicle (e.g., errands, official visits).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='If it’s an office car, record which staff is currently using it.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.staff'),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_consumption_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fuel used over time (optional for office cars).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='vehicle_type',
            field=models.CharField(choices=[('CARGO', 'Cargo Truck'), ('OFFICE', 'Office Car')], default='CARGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, help_text='Additional details for this expense', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='OfficeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, help_text='Liters of fuel consumed', max_digits=7, null=True)),
                ('purpose', models.CharField(blank=True, help_text='Reason for usage (e.g. errands, official visits).', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('truck', models.ForeignKey(help_text='Select the office car', limit_choices_to={'vehicle_type': 'OFFICE'}, on_delete=django.db.models.deletion.CASCADE, to='transportation.truck')),
                ('user', models.ForeignKey(blank=True, help_text='Staff member who used the car (not necessarily a driver).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.staff')),
            ],
        ),
    ]
