# Generated by Django 5.1 on 2025-03-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_gpsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.JSONField(blank=True, help_text='Stores the route points as the truck moves.', null=True),
        ),
    ]
