# Generated by Django 5.1 on 2025-03-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_trip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.JSONField(blank=True, default=list, help_text='Array of route points for this trip.'),
        ),
    ]
