# Generated by Django 5.1 on 2025-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_alter_trip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.JSONField(blank=True, help_text='Stores the route points as the truck moves.', null=True),
        ),
    ]
