# Generated by Django 5.1 on 2025-03-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_alter_trip_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='attached_image',
            field=models.ImageField(blank=True, help_text='Upload invoice image', null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='transportation.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargo_load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='final_kilometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='initial_kilometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_in_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tariff_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
