# Generated by Django 5.1 on 2025-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_remove_invoice_issue_date_invoice_attached_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
