# Generated by Django 5.1 on 2025-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ነዳጅ', 'ነዳጅ'), ('አጋዥ', 'አጋዥ'), ('መንገድ ፈንድ', 'መንገድ ፈንድ'), ('ፍተሻ', 'ፍተሻ'), ('ሰንሰለት', 'ሰንሰለት'), ('ሚዛን', 'ሚዛን'), ('መንገድ ትራንስፖርት', 'መንገድ ትራንስፖርት'), ('ጥገና', 'ጥገና'), ('ጎማ፣ ደብራተር እና ነፋስ', 'ጎማ፣ ደብራተር እና ነፋስ'), ('የሹፌር አበል', 'የሹፌር አበል'), ('ቻይና/ዶላሬ መግቢያ', 'ቻይና/ዶላሬ መግቢያ'), ('ደላላ', 'ደላላ'), ('የደረሰኝ ወጪ', 'የደረሰኝ ወጪ'), ('መኪና ጥበቃ እና ማሳደሪያ', 'መኪና ጥበቃ እና ማሳደሪያ'), ('የመኪና እጥበት', 'የመኪና እጥበት'), ('ሰርቪስ/ታፒሰሪ', 'ሰርቪስ/ታፒሰሪ'), ('ታፒሰሪ', 'ታፒሰሪ'), ('የመኪና ማሳደሪያ', 'የመኪና ማሳደሪያ'), ('ተሳቢ ማዘያ እና ማውረጃ', 'ተሳቢ ማዘያ እና ማውረጃ'), ('Other', 'Other')], default='ነዳጅ', max_length=50),
        ),
    ]
