# Generated by Django 5.1 on 2025-03-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
