# Generated by Django 4.2.19 on 2025-03-24 18:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0012_remove_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpenseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount given at this instance', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('image', models.ImageField(blank=True, help_text='Upload a receipt or related image', null=True, upload_to='operational_expense_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('financial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_details', to='transportation.tripfinancial')),
            ],
        ),
    ]
