# Generated by Django 4.2.19 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_operationalexpensedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalexpensedetail',
            name='note',
            field=models.CharField(blank=True, help_text='Optional description or comment about this expense.', max_length=255, null=True),
        ),
    ]
