# Generated by Django 4.2.19 on 2025-09-16 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transportation', '0014_operationalexpensedetail_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('circle', 'Circle'), ('rect', 'Rectangle'), ('polygon', 'Polygon')], max_length=16)),
                ('geometry', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='transportation.truck')),
            ],
            options={
                'indexes': [models.Index(fields=['truck', 'active'], name='transportat_truck_i_fcabbf_idx')],
            },
        ),
    ]
