# Generated by Django 4.2.19 on 2025-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0015_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
