# Generated by Django 4.2.19 on 2025-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0016_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='truck_trip_number',
            field=models.PositiveIntegerField(blank=True, help_text='Per-truck trip sequence number', null=True),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('truck', 'truck_trip_number'), name='uniq_truck_trip_number_per_truck'),
        ),
    ]
