# Generated by Django 4.2.19 on 2025-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0017_trip_truck_trip_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripfinancial',
            name='net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Net profit margin as a percentage (one decimal), calculated as (income_before_tax / total_revenue) * 100.', max_digits=5, null=True),
        ),
    ]
