# Generated by Django 4.2.19 on 2025-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0018_alter_tripfinancial_net_profit_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completion_notified',
            field=models.BooleanField(default=False, help_text='Whether completion email was sent to management.'),
        ),
    ]
