# Generated by Django 4.2.19 on 2025-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0019_trip_completion_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CLERK', 'Clerk'), ('DRIVER', 'Driver')], default='OTHER', max_length=20),
        ),
    ]
