# Generated by Django 4.2.19 on 2025-11-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='large_txn_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
