# Generated by Django 4.2.19 on 2025-11-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='cash/attachments/'),
        ),
    ]

