# Generated by Django 4.2.19 on 2025-11-12 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0005_transaction_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=16)),
                ('source', models.CharField(default='CBE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'currency'],
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
